services:
  api:
    build: ./backend
    container_name: api
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: db
    restart: always
    tty: true
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clientsandcontacts
